version: '3.7'
services:
  database:
    image: postgres:13.1-alpine
    container_name: database-chatbot-service
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres